apiVersion: v1
kind: Service
metadata:
  labels:
    app: shipping-service-app
  name: shipping-service-service
  namespace: spring-boot-namespace
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: shipping-service-app
  type: ClusterIP
status:
  loadBalancer: {}
