apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipping-service-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ahramadan/shippingservice.git
    targetRevision: HEAD
    path: kube
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-boot-namespace